- name: test raw module
  hosts: "{{server_name}}"
  tasks:
    - name: downloading a file
      raw: Copy-Item -Path \\GB3GOCHJRGTST03\c$\sysadmin\Runner -Destination C:\sysadmin\Runner -Force -recurse
      register: out
    - debug: var=out
