- name: File Copy
  hosts: "{{server_name}}"
  tasks:
    - name: map drive
      raw: 'net use i: \\GB3GOCHJRGTST03\c$\sysadmin "{{ansible_ssh_pass}}" /user:"{{ansible_ssh_user}}"'
    - name: Copy Runner Folder
      raw: 'Copy-Item -Path i:\Runner -Destination c:\sysadmin\Runner -Force -recurse'
    - name: List DIR
      raw: 'dir i:'
      register: out
    - debug: var=out
