- name: test raw module
  hosts: "{{server_name}}"
  tasks:
    - name: Map network share
      raw: net use I: \\GB3GOCHJRGTST03\c$\sysadmin\Runner /user:"{{ansible_ssh_user}}" /password:"{{ansible_ssh_pass}}"
    - name: Copy Runner Folder
      raw: Copy-Item -Path I:\ -Destination \\GB3GOCHJRGTST02\c$\sysadmin\Runner -Force -recurse
      register: out
    - debug: var=out
