- name: test raw module
  hosts: "{{server_name}}"
  tasks:
    - name: Copy Runner Folder
      command: Copy-Item -Path \\GB3GOCHJRGTST03\c$\sysadmin\Runner -Destination C:\sysadmin\Runner -Force -recurse
      register: out
    - debug: var=out
