- name: test raw module
  hosts: "{{server_name}}"
  tasks:
    - name: Copy Runner Folder
      raw: Copy-Item -Path \\GB3GOCHJRGTST03\c$\sysadmin\Runner -Destination \\GB3GOCHJRGTST02\c$\sysadmin\Runner -Force -recurse
      register: out
    - debug: var=out
