---
- name: Run Powershell Playbook
  hosts: localhost
  tasks:
    - name: Run kerberos install
      script: kerberos.py
- name: Run Powershell Playbook
  hosts: "{{server_name}}"
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
