
---
- name: Run Powershell Playbook
  hosts: "{{server_name}}"
  remote_user: "{{user_name}}"
  become: yes
  become_user: "{{user_name}}"
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
