---
- ansible_winrm_transport: kerberos
- ansible_winrm_kerberos_delegation: yes
- name: Run Powershell Playbook
  hosts: "{{server_name}}"
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
