---
- name: test raw module
  hosts: localhost
  tasks:
    - name: run a powershell script
      script: winrm_mem.py
       -s "{{server_name}}"
       -u "{{user}}"
       -p "{{password}}"
      register: out
    - debug: var=out
