---
- name: Run Powershell Playbook
  hosts: "{{server_name}}"
  vars:
  ansible_winrm_transport: kerberos
  ansible_ssh_pass: "{{ansible_ssh_pass}}"
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
