---
- name: Run Powershell Script Playbook
  hosts: "{{server_name}}"
  tasks:
    - name: Fetch stuff from the remote and save to local
      synchronize:  
        src: \\GB3GOCHJRGTST03\c$\sysadmin\Runner\
        dest: C:\sysadmin\Runner\
        mode: pull
        with_items:
         - "Runner"
    - name: Run Powershell Script "{{script_name}}"
      script: "{{script_name}}"
