---
- name: Run Powershell Playbook
  ansible_winrm_transport: kerberos
  ansible_winrm_kerberos_delegation: yes
  hosts: "{{server_name}}"
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
