---
- name: Run Powershell Script Playbook
  hosts: "{{server_name}}"
  tasks:
    - name: map drive
      raw: 'net use i: \\GB3GOCHJRGTST03\c$\sysadmin\Runner "{{ansible_ssh_pass}}" /user:"{{ansible_ssh_user}}" /PERSISTENT:YES; dir i:\'
    - name: Run Powershell Script "{{script_name}}"
      script: "{{script_name}}"
