---
- name: Run Powershell Playbook
  hosts: "{{server_name}}"
  ansible_password: "{{ansible_ssh_pass}}"
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
