---
- name: Run Powershell Playbook
  hosts: localhost
  tasks:
    - name: Run a Powershell Script
      script: winrm_ipconfig.py
       -s "{{server_name}}"
       -u "{{user}}"
       -p "{{password}}"
      register: out
    - debug: var=out
