---
- name: Start a script on host
  hosts: "{{server_name}}"
  gather_facts: False
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: ntlm
  tasks:
    - name: Run a Powershell Script
      script: "{{script_name}}"
      register: out
