---
- name: Start a script on host
  hosts: "{{server_name}}"
  gather_facts: False
  vars:
    ansible_connection: winrm
    ansible_winrm_transport: html
  tasks:
    - name: Run a Powershell Script
      script: scripts/mem.ps1
      register: out
